# Generated by Django 3.2 on 2021-04-22 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="degree",
            field=models.CharField(default="professor", max_length=30),
        ),
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="homework",
            name="text",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="solution",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
    ]
